### ISSUE TITLE
Çocuk Düzenleme

### ISSUE THREAD

**Issue by tarikemre** [enescakir/leyladan-sonra-web#44]
Çocukları düzenlerken departman ve dilek kategorisi kısmı boş görünüyor

**Comment by SmtSmnc** [comment]
Yeni sisteme sanırım onların eklenmesi gerekecek Tarık, sistemde de görünmüyor

**Comment by enescakir** [comment]
`Departman` ve `Dilek Kategorisi` listesinin `Ayarlar` kısmından sisteme eklemesi gerekiyor. 

Şu an eklenmiş olarak gözüküyor
