### ISSUE TITLE
Yetkilendirme>>>Çocuğun hediyesi ulaştı, yolda gibi durumunu güncellemeleri normal üyeler kendi çocuklarını, diğer üst yetkililer fakültedeki tüm çocuklarınkini yapabilmeli

### ISSUE THREAD

**Issue by SmtSmnc** [enescakir/leyladan-sonra-web#46]

**Comment by enescakir** [comment]
Aşağıdakiler yetkilendirmeler doğru mu? @SmtSmnc 

#### Ziyaret Etme:
- Herkes
#### Tekrardan `Bekleniyor` yapma :
- Fakülte Sorumlusu
- Fakülte Yönetim Kurulu
#### `Gönüllü bulundu`, `Hediyesi geldi`, `Teslim edildi` işlemleri :
- Fakülte Sorumlusu
- Fakülte Yönetim Kurulu
- İletişim Sorumlusu
- Hediye Sorumlusu
- Site Sorumlusu
- Çocuğun Sorumluları
