### ISSUE TITLE
Çocukların hediye teslim yazıları yüklenince sistem üzerinde teslim edildi olarak görünmesi için görevlinin onayı gerekiyor

### ISSUE THREAD

**Issue by tarikemre** [enescakir/leyladan-sonra-web#51]
Eğer teslim yazısı yüklenince "teslim edildi" olarak görülmesi mümkün olursa güzel olur. Yani eski sistemde olduğu gibi

**Comment by enescakir** [comment]
Çocuğun hediye teslim yazısı onayladığında durumu da `Teslim Edildi` olarak güncelleniyor artık 🎉
