### ISSUE TITLE
Ekiplere gelen mailler sistemde alfabetik sıralanıyor. Mümkünse eski sistemdeki gibi tarihe göre sıralansa daha iyi olur.

### ISSUE THREAD

**Issue by tarikemre** [enescakir/leyladan-sonra-web#52]

**Comment by enescakir** [comment]
_Sohbetler_ sayfasındaki _Çocuklar_ sekmesi altındaki sıramalayı mı kastediyorsun? @tarikemre

**Comment by tarikemre** [comment]
Aynen abi. Bahsettiğin yerdeki sıralamayı kastediyorum

**Comment by tarikemre** [comment]
O sekmede çocuk için bize ulaşan gönüllüler alfabetik sıralanıyor zaman sıralaması yerine

**Comment by enescakir** [comment]
Sıralamayı düzelttim ⬇️ ⬆️
