### ISSUE TITLE
Ekiplere gelen maillerin bildirimleri sistemde görünmüyor

### ISSUE THREAD

**Issue by tarikemre** [enescakir/leyladan-sonra-web#53]

**Comment by enescakir** [comment]
Bunu biraz daha detaylandırabilir misin? Anlayamadım

**Comment by tarikemre** [comment]
Detayları öğrenir öğrenmez atıyorum 👍

**Comment by tarikemre** [comment]
Önceki sistemde mail gelince mail görevlilerinin kendi mail hesaplarına bildirim geliyordu gönüllü mail attı diye. Bildirimden kasıt o abi

**Comment by enescakir** [comment]
Bu sistemde de var aslında. Gönüllüden mesaj gelince fakültedeki iletişim sorumlularına aşağıdaki gibi bildirim gidiyor.

Eğer bildirim gitmeyen spesifik fakülte ya da kişi varsa ona bakabilirim.
Bir de sadece yeni mesaj bildirimleri mi gelmiyormuş yoksa diğer bildirimler de mi gelmiyor?

<img width="850" alt="message_notification" src="https://user-images.githubusercontent.com/993199/82568864-1c3f7600-9b88-11ea-951b-a89a5c5a4ed5.png">

**Comment by tarikemre** [comment]
Abi bundan sonra kişi ve fakülte olarak bu şikayeti alıp iletirim sana
