### ISSUE TITLE
Durdurulan veya aktiflikten çıkarılan fakülteler sistemde durdurulmuş görünmesine rağmen anasayfada aktif olarak görünüyor

### ISSUE THREAD

**Issue by tarikemre** [enescakir/leyladan-sonra-web#56]

**Comment by enescakir** [comment]
Aktif ve Görüşülenin yanına bir de Durdurulan diye bir kategori ekledim.

İsterseniz bu kategorilerin altına küçük bir açıklama ekleyebiliriz. @tarikemre 
Aşağıdaki tarzda açıklamalar oluşturursanız ekleyebiliriz.
**Aktif** ➔ Aktif olarak miniklerimizi ziyaret ettiğimiz ve dileklerini kabul ettiğimiz fakülteler
**Görüşülen** ➔ Projemizi başlatmak için görüştüğümüz fakülteler
**Durdurulan** ➔ Bazı sebeplerden dolayı projemizi devam ettiremediğimiz fakülteler

**Comment by tarikemre** [comment]
Durdurulan için➡️ Bazı sebeplerden dolayı projemize ara verdiğimiz fakülteler
şeklinde yapabiliriz. Geri kalan kısmı da senin dediğin gibi olabilir abi

**Comment by enescakir** [comment]
Ekledim 🎉
